# Generated by Django 4.1.3 on 2022-12-09 02:16

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="String from 3 to 64 chars",
                        max_length=64,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="String from 3 to 64 chars",
                        max_length=64,
                        validators=[django.core.validators.MinLengthValidator(3)],
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="E-mail in valid format", max_length=254, unique=True
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("admin", "Администратор"), ("user", "Пользователь")],
                        default="user",
                        max_length=10,
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        help_text="+7(___)___-__-__", max_length=12, region=None
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="user_avatars/"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
